### ISSUE TITLE
SoftwareSerial and WifiESP

### ISSUE THREAD

**Issue by andrekiba** [ppedro74/Arduino-SerialCommands#1]
I and thanks in advance. Nice idea this library but it doesn't work with SoftwareSerial and WifiEsp.
Can you confirm this? Otherwise can you provide a working example?
I tried something like this without success.

```c++
SoftwareSerial wifiSerial(2, 3);

char serialCommandBuffer[32];
SerialCommands serialCommands(&wifiSerial, serialCommandBuffer, sizeof(serialCommandBuffer), "\r\n", " ");

void unrecognizedCmd(SerialCommands* sender, const char* cmd)
{
  Stream* serial = sender->GetSerial();
  serial->print("ERROR: Unrecognized command [");
  serial->print(cmd);
  serial->println("]");
}

void execHelloCmd(SerialCommands* sender)
{
  sender->GetSerial()->println("Hello!");
}

void execLedOnCmd(SerialCommands* sender)
{
  digitalWrite(13, HIGH);  
  sender->GetSerial()->println("Led is on");
}

void execLedOffCmd(SerialCommands* sender)
{
  digitalWrite(13, LOW);  
  sender->GetSerial()->println("Led is off");
}

SerialCommand helloCmd("HELLO", execHelloCmd);
SerialCommand ledOnCmd("ON", execLedOnCmd);
SerialCommand ledOffCmd("OFF", execLedOffCmd);

void setup()
{
  Serial.begin(115200);
  wifiSerial.begin(9600);

  WiFi.init(&wifiSerial);

  status = WiFi.beginAP(ssid, 10, pass, ENC_TYPE_WPA2_PSK, true);

  server.begin();

  serialCommands.SetDefaultHandler(unrecognizedCmd);
  serialCommands.AddCommand(&helloCmd);
  serialCommands.AddCommand(&ledOnCmd);
  serialCommands.AddCommand(&ledOffCmd);
}

void loop()
{
  WiFiEspClient client = server.available();
  if (client)
  { 
    if (client.connected()) 
      serialCommands.ReadSerial();
    delay(10);
    client.stop();
    }
}

```

**Comment by andrekiba** [comment]
And how I need to define SERIAL_COMMANDS_DEBUG to be able to "debug" your library?

**Comment by ppedro74** [comment]
The original SoftwareSerial has poor performance and is very sensitive to code implementations (e.g delays and other code logics). 

you can read more here:
https://www.pjrc.com/teensy/td_libs_AltSoftSerial.html

I did an example: 
https://github.com/ppedro74/arduino-playground/blob/master/SerialSoftwareTest/SerialSoftwareTest.ino

using both SoftwareSerial and AltSoftSerial (commented) and both libraries work with my Arduino UNO.

**Comment by ppedro74** [comment]
Regarding the library debug you can open the SerialCommands.h (Library file) and remove the comment line 7:
//#define SERIAL_COMMANDS_DEBUG

**Comment by tggo** [comment]
on starting ESP send to Serial some trash info and buffer is overflow
